# Generated by Django 4.0 on 2023-02-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlyphUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('attack', models.CharField(max_length=200)),
                ('attribute', models.CharField(max_length=200)),
                ('consume', models.CharField(max_length=200)),
                ('effect', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('comb1', models.CharField(max_length=200)),
                ('comb2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('attributes', models.CharField(max_length=200)),
                ('statistics', models.CharField(max_length=200)),
                ('found', models.CharField(max_length=200)),
                ('consume', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
    ]
