# Generated by Django 4.0 on 2023-02-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_glyphunion_comb1_remove_glyphunion_comb2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
