# Generated by Django 4.0 on 2023-02-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_weapon_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='glyphunion',
            name='alias',
            field=models.CharField(default='aa', max_length=200),
            preserve_default=False,
        ),
    ]
