# Generated by Django 4.0 on 2023-02-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_glyphunion_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='alias',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
